export type Lesson = {
  id: string;
  title: string;
  summary: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  body: string;
  deepDive: string;
};

export type Track = {
  slug: string;
  number: string;
  title: string;
  description: string;
  lessons: Lesson[];
  accent: string;
};

const make = (id: string, title: string, summary: string, level: Lesson["level"], body: string, deepDive: string): Lesson => ({ id, title, summary, level, body, deepDive });

const crypto101: Lesson[] = [
  make("01", "What is money?", "Why humans use money and what makes something useful as money.", "Beginner", "Money is a shared system for storing and exchanging value. It works because people agree that a unit can be used to settle a future obligation. Over time, societies moved from physical commodities to government-issued currency and digital balances.", "The important properties are scarcity, divisibility, portability, durability, recognizability and resistance to unwanted changes. Crypto experiments with digital scarcity and settlement without requiring a single issuer to maintain the ledger."),
  make("02", "What is cryptocurrency?", "The core idea behind digitally native assets.", "Beginner", "A cryptocurrency is a digital asset whose ownership and transfers are recorded by a blockchain or similar distributed system. Instead of a bank keeping the only authoritative database, a network of computers follows shared rules.", "Crypto is broader than coins used as money. Tokens can represent utility, governance rights, claims on assets, or programmable value inside applications."),
  make("03", "What is Bitcoin?", "The problem Bitcoin was designed to solve.", "Beginner", "Bitcoin is a decentralized monetary network launched in 2009. It lets participants transfer value over the internet while a public blockchain records the transaction history.", "Bitcoin combines proof-of-work mining, a fixed issuance schedule and public verification rules. Its design trades some speed and flexibility for strong settlement assurances and censorship resistance."),
  make("04", "What is a blockchain?", "The shared ledger underneath many crypto networks.", "Beginner", "A blockchain is a replicated ledger organized into ordered blocks. Network participants verify proposed transactions and agree on which valid block comes next.", "The key innovation is not simply a database. It is a coordination system where independent parties can converge on the same history using cryptography, incentives and consensus rules."),
  make("05", "How does a transaction work?", "From signing a message to network confirmation.", "Beginner", "A wallet creates a transaction and signs it with a private key. Nodes check whether the transaction follows the network rules, then miners or validators include it in a block.", "A confirmation is evidence that a transaction has been included in the canonical chain. More confirmations generally increase confidence, although the exact security model depends on the network."),
  make("06", "Wallets and private keys", "How keys let you control on-chain assets.", "Beginner", "A crypto wallet does not literally contain coins. It manages cryptographic keys that let you prove control over addresses and authorize transactions.", "A private key must remain secret. A seed phrase is commonly used to derive wallet keys. Losing the recovery material can mean losing access, while exposing it can give another person control."),
  make("07", "Public addresses", "The identifier other people use to send assets to you.", "Beginner", "A public address is derived from cryptographic information and can be shared. It tells a network where an asset transfer should be recorded.", "Addresses differ between networks and address formats. Always verify the destination network before sending funds because similar-looking addresses can still represent different systems."),
  make("08", "Centralized exchanges", "How crypto exchanges connect users to markets.", "Beginner", "A centralized exchange is a company-operated platform where users deposit assets and trade against other participants. The exchange maintains internal account balances and an order book.", "The convenience comes with counterparty and custody risk. Users should understand fees, withdrawal rules, proof-of-reserves claims, security controls and the distinction between exchange balances and on-chain ownership."),
  make("09", "Stablecoins", "Crypto assets designed to track a reference value.", "Beginner", "Stablecoins aim to keep a relatively stable price, often around a fiat currency such as the US dollar. They are widely used for settlement, trading and DeFi.", "Different stablecoins use different mechanisms: cash or asset reserves, overcollateralized crypto, or algorithmic designs. Their risks therefore depend on collateral, redemption, governance and liquidity."),
  make("10", "Gas fees", "Why blockchain transactions cost money.", "Beginner", "Networks charge fees to compensate the infrastructure that processes transactions and to prevent unlimited spam. On smart-contract chains, more computation can require more gas.", "Gas price and gas used are separate concepts. A transaction can be computationally simple but expensive during congestion, while a complex transaction can consume more gas even when the network is quiet."),
  make("11", "Custody and self-custody", "The difference between holding assets yourself and using a provider.", "Beginner", "With self-custody, you control the keys. With custodial services, a provider controls the keys while you receive an account claim against its system.", "Self-custody removes some intermediary risk but creates operational responsibility. Good security practices include hardware wallets, backups, device hygiene and careful transaction verification."),
  make("12", "Crypto vocabulary", "The essential words that make the rest of the industry easier to understand.", "Beginner", "Terms such as address, block, node, validator, liquidity, market cap, token, protocol and smart contract appear everywhere in crypto. Learning the vocabulary makes technical explanations much easier to follow.", "Crypto concepts are connected. For example, a token may live on a blockchain, trade on an exchange, be held in a wallet, and interact with a smart contract. Build the mental model rather than memorizing isolated definitions."),
];

const howCryptoWorks: Lesson[] = [
  make("01", "Blocks", "How transactions are packaged into an ordered history.", "Beginner", "Blocks group valid transactions into batches that can be referenced by later blocks. This creates a tamper-evident sequence of state changes.", "Block headers typically commit to previous history and transaction data. Changing an old block changes the cryptographic commitments that follow it."),
  make("02", "Nodes", "The computers that participate in a blockchain network.", "Beginner", "Nodes receive transactions and blocks, verify them against protocol rules, and share valid information with peers.", "Different node types can have different responsibilities. Full nodes independently verify the chain instead of trusting another party's database."),
  make("03", "Peer-to-peer networks", "How blockchain participants communicate without one central server.", "Beginner", "Crypto networks use peer-to-peer communication so information can travel between many independent machines.", "Peer discovery, gossip protocols, latency and network topology affect how quickly transactions and blocks propagate."),
  make("04", "Consensus", "How distributed computers agree on one valid chain.", "Intermediate", "Consensus is the mechanism that lets a network converge on a shared state even when participants do not fully trust one another.", "Consensus rules determine who can propose blocks, how conflicts are resolved and what economic or computational costs discourage dishonest behavior."),
  make("05", "Proof of Work", "How Bitcoin uses computation to secure its chain.", "Intermediate", "Miners compete to find a valid proof by performing large numbers of hash calculations. The winning block can then be accepted by other nodes.", "Proof of work turns energy and hardware expenditure into a Sybil-resistance mechanism. Attackers would need substantial resources to rewrite recent history."),
  make("06", "Proof of Stake", "How validators secure networks using economic collateral.", "Intermediate", "Proof-of-stake networks select validators according to protocol rules and require them to commit capital that can be penalized for certain dishonest behavior.", "Staking changes the resource model from external computation to internal economic security. Slashing and validator incentives become important parts of the design."),
  make("07", "Validators", "The participants that help process and attest to transactions.", "Intermediate", "Validators perform protocol duties such as proposing, checking or attesting to blocks, depending on the network.", "Validator rewards, penalties, uptime requirements and client diversity all influence the resilience of a proof-of-stake system."),
  make("08", "Finality", "When a transaction becomes increasingly difficult or impossible to reverse.", "Intermediate", "Finality describes the point at which a blockchain treats a state as settled under its consensus model.", "Some networks provide probabilistic finality while others provide explicit economic or protocol finality. The distinction matters for exchanges and bridges."),
  make("09", "Smart contracts", "Programs that execute according to blockchain rules.", "Beginner", "Smart contracts are programs deployed to a blockchain. Users interact with them by submitting transactions that cause predefined logic to run.", "Smart contracts are deterministic within their execution environment. Bugs can become financial risks because deployed code may control valuable assets."),
  make("10", "Ethereum", "A programmable blockchain and application platform.", "Beginner", "Ethereum extends blockchain functionality beyond simple transfers by providing a general execution environment for smart contracts.", "Ethereum's execution, consensus and data layers work together. Its ecosystem supports tokens, DeFi, NFTs, DAOs and many scaling systems."),
  make("11", "Accounts and contracts", "The two major kinds of stateful actors on Ethereum.", "Intermediate", "Ethereum distinguishes externally controlled accounts from contract accounts. Users sign transactions, while contracts execute code when called.", "Understanding this model explains why wallets, contract addresses, approvals and transaction calldata appear together in Ethereum applications."),
  make("12", "Transactions and gas", "How Ethereum prices computation.", "Intermediate", "Ethereum transactions specify gas-related parameters that determine how much computation the sender is willing to pay for.", "Gas makes scarce blockspace economically allocatable. When demand rises, users compete for inclusion and fees can increase."),
  make("13", "Layer 1", "The base blockchain where core settlement occurs.", "Beginner", "A Layer 1 is a base network with its own consensus and native asset. Bitcoin and Ethereum are examples.", "Layer 1 design balances security, decentralization, execution capacity and data availability. Different chains make different tradeoffs."),
  make("14", "Layer 2", "Scaling systems that build on top of a base chain.", "Intermediate", "Layer 2 systems process activity away from the base layer while using the underlying chain for security, settlement or data.", "Rollups are a major Layer 2 family. They batch many operations and publish enough data or proofs for the base chain to verify the resulting state."),
  make("15", "Rollups", "A practical approach to scaling smart-contract networks.", "Advanced", "Rollups execute transactions on a secondary environment and periodically anchor their results to a base chain.", "Optimistic and zero-knowledge rollups use different verification models. Their bridges, sequencers and data publication choices create different trust assumptions."),
  make("16", "Oracles", "How smart contracts access information from outside their chain.", "Intermediate", "Blockchains cannot natively observe arbitrary external data. Oracles provide data such as prices to contracts.", "Oracle design is a security problem. Manipulated prices can cause lending markets, derivatives and other protocols to make dangerous decisions."),
  make("17", "Bridges", "How assets and messages move between blockchain ecosystems.", "Intermediate", "Bridges create a connection between separate networks so users can transfer assets or messages across them.", "Bridges can introduce additional trust assumptions, validators, proofs and smart-contract risk. Their security history is an important part of crypto's infrastructure story."),
  make("18", "Blockspace economics", "Why blockspace behaves like a scarce digital resource.", "Advanced", "Each blockchain has finite capacity per unit of time. Users compete for that capacity through transaction fees or other mechanisms.", "Blockspace economics links network demand, fee markets, application design, MEV and validator incentives into one system. It is a useful lens for understanding why networks behave differently under load."),
];

const markets: Lesson[] = [
  make("01", "What is a market?", "How buyers and sellers discover prices.", "Beginner", "A market is a system where buyers and sellers exchange assets. Price emerges from the interaction of available supply and demand.", "Crypto markets can be fragmented across centralized exchanges, decentralized exchanges and regions, which creates differences in liquidity and price."),
  make("02", "Market cap", "A simple measure of the value of circulating tokens.", "Beginner", "Market capitalization is generally calculated as token price multiplied by circulating supply.", "Market cap is useful but incomplete. It does not tell you how much capital could actually be withdrawn at the displayed price or how concentrated ownership is."),
  make("03", "FDV", "Fully diluted valuation and why token supply matters.", "Beginner", "FDV multiplies price by the total or maximum token supply defined by the project model.", "Comparing market cap with FDV helps reveal future dilution from tokens that have not yet entered circulation."),
  make("04", "Liquidity", "Why some markets can absorb trades better than others.", "Beginner", "Liquidity describes how much buying or selling can happen without moving price significantly.", "Depth, spreads, volume and market structure all influence execution quality. A market can show high volume while still having weak liquidity at certain prices."),
  make("05", "Order books", "The live list of bids and asks on an exchange.", "Beginner", "An order book displays buy orders and sell orders at different prices. The closest bid and ask form the visible spread.", "Order-book depth can change quickly. Large orders can consume several price levels and create slippage."),
  make("06", "Bid, ask and spread", "The three basic numbers behind a tradable market.", "Beginner", "The bid is the highest visible buying price, the ask is the lowest visible selling price, and the spread is the difference between them.", "Tighter spreads usually indicate more competitive liquidity, although the best displayed quote is not the only measure of execution quality."),
  make("07", "Market orders", "Trading immediately against available liquidity.", "Beginner", "A market order prioritizes execution over a specific price. It consumes the best available offers or bids until the requested size is filled.", "Large market orders can move through multiple levels. This is why execution price can differ from the price shown before the order is placed."),
  make("08", "Limit orders", "Trading only at a chosen price or better.", "Beginner", "A limit order specifies the worst acceptable price. It can provide price control but may not fill.", "Limit orders can add liquidity when they rest on the book. Whether they are maker or taker orders depends on how the exchange classifies execution."),
  make("09", "Maker and taker fees", "How exchanges charge for providing and consuming liquidity.", "Beginner", "A maker adds a resting order to the book, while a taker removes liquidity with an order that executes immediately.", "Fee schedules often depend on volume tiers, product type and account status. Small fee differences can compound for active traders."),
  make("10", "Slippage", "The difference between expected and executed price.", "Beginner", "Slippage happens when the available market depth cannot fill an order at one price. The trade then executes across multiple levels or at changing prices.", "Slippage depends on order size, liquidity, volatility and execution speed. It is a core concept for both centralized and decentralized trading."),
  make("11", "Spot trading", "Buying or selling the underlying crypto asset.", "Beginner", "Spot trading exchanges one asset for another at current market conditions. After settlement, the buyer generally owns the purchased asset.", "Spot markets form the reference for many derivatives and DeFi applications. Custody and withdrawal rules matter because ownership may remain on the exchange."),
  make("12", "Futures", "Contracts whose value tracks an underlying asset.", "Intermediate", "Futures are derivatives that create an obligation or exposure tied to an underlying asset at specified terms.", "Crypto futures can support hedging and speculation but introduce margin, leverage, funding and liquidation mechanics that do not exist in simple spot ownership."),
  make("13", "Perpetual contracts", "Futures-like products without a fixed expiry date.", "Intermediate", "Perpetuals allow traders to maintain leveraged exposure without a traditional expiration date.", "Because perpetuals do not expire, exchanges use mechanisms such as funding payments to keep contract prices aligned with the underlying market."),
  make("14", "Leverage", "Using borrowed or reserved capital to increase exposure.", "Beginner", "Leverage lets a trader control a larger position relative to their own margin. It magnifies both gains and losses.", "A highly leveraged position has a smaller margin buffer. Small adverse price moves can therefore trigger liquidation."),
  make("15", "Margin", "The collateral backing a leveraged position.", "Beginner", "Margin is the capital committed to support a leveraged trade. Exchanges monitor it against the position's risk.", "Initial margin opens a position while maintenance margin is the minimum collateral threshold required to keep it open."),
  make("16", "Liquidation", "Why a leveraged position can be forcibly closed.", "Beginner", "If losses reduce available collateral below the required maintenance level, the exchange can close the position to limit further losses.", "Liquidation price depends on entry price, leverage, position size, maintenance requirements, fees and other positions in the account."),
  make("17", "Funding rate", "The periodic payment mechanism used by perpetual markets.", "Intermediate", "Funding transfers value between long and short traders according to a rate determined by the market structure.", "Funding is designed to keep perpetual prices near the underlying reference. The exact formula varies by exchange and product."),
  make("18", "Mark price", "A reference price used for risk calculations.", "Intermediate", "The mark price is a robust reference used by many derivatives venues to calculate unrealized P&L and liquidation rather than relying only on the last traded price.", "Using a reference price reduces the ability of a single unusual trade to trigger unnecessary liquidations."),
  make("19", "Index price", "A composite reference built from underlying markets.", "Intermediate", "An index price aggregates prices from selected spot markets to represent the underlying asset's fair market level.", "Index construction, source selection and weighting affect derivatives risk management. Exchanges publish their methodology for transparency."),
  make("20", "Open interest", "The total outstanding exposure in derivatives contracts.", "Intermediate", "Open interest measures contracts that remain open rather than already closed. It helps describe how much derivatives exposure exists.", "Open interest should be interpreted alongside price, volume and funding. Rising open interest can accompany both bullish and bearish positioning."),
  make("21", "Volume", "How much trading activity happened during a period.", "Beginner", "Trading volume measures the amount of assets or contracts exchanged over a period.", "Volume can indicate participation, but reported volume quality varies. Wash trading and fragmented markets can make raw numbers misleading."),
  make("22", "Volatility", "How quickly and widely prices move.", "Beginner", "Volatility measures the magnitude of price variation. Crypto markets can experience large moves over short periods.", "Volatility affects option pricing, liquidation risk, position sizing and the cost of market making."),
  make("23", "Risk management", "The discipline of limiting losses before entering a trade.", "Beginner", "Risk management includes position sizing, leverage limits, stop conditions and diversification of operational risks.", "A robust process focuses on expected loss rather than only expected return. No strategy can remove market risk entirely."),
  make("24", "Trading psychology", "How behavior affects decision-making in volatile markets.", "Beginner", "Fear, greed, overconfidence and loss aversion can change how people execute a plan.", "A written trading process, predefined risk limits and post-trade review can reduce impulsive decisions. Education is not a guarantee of profit."),
];

const tokenomics: Lesson[] = [
  make("01", "What is a token?", "A digital unit used inside a crypto ecosystem.", "Beginner", "A token is a digital representation recorded on a blockchain. It can be used for utility, governance, access, rewards or other economic functions.", "Token standards define how contracts represent balances, transfers and approvals. A token's value ultimately depends on its utility, demand and market structure."),
  make("02", "Circulating supply", "The amount of a token considered publicly available.", "Beginner", "Circulating supply is an estimate of tokens currently available in the market rather than locked, vested or otherwise restricted supply.", "Different data providers can use different definitions. Always check methodology when comparing market-cap figures."),
  make("03", "Total supply", "How much of a token exists under the current protocol rules.", "Beginner", "Total supply generally describes tokens that have been created, excluding amounts that have been permanently removed depending on the definition used.", "Minting and burning rules can change total supply over time. Read the protocol documentation rather than assuming supply is fixed."),
  make("04", "Maximum supply", "A protocol's upper bound on token creation when one exists.", "Beginner", "Some tokens have a maximum supply, while others allow ongoing issuance according to protocol rules.", "A fixed maximum does not automatically create scarcity if demand is weak. Monetary policy must be evaluated alongside utility and adoption."),
  make("05", "Token unlocks", "When previously restricted tokens become transferable.", "Beginner", "An unlock releases tokens from a vesting or lockup schedule. It can increase circulating supply.", "Unlocks can create potential selling pressure, but price impact depends on who receives the tokens, their incentives and existing market liquidity."),
  make("06", "Vesting", "A schedule controlling when tokens become available.", "Beginner", "Vesting gradually releases tokens to teams, investors or other stakeholders according to predetermined rules.", "Common schedules include cliffs followed by linear vesting. Transparency around vesting helps users understand future dilution."),
  make("07", "Inflation", "When token supply increases over time.", "Beginner", "Inflation means the supply of a token grows according to its issuance rules.", "Inflation can fund validators, miners or ecosystem incentives. The key question is whether network demand grows fast enough to absorb new supply."),
  make("08", "Deflation and burns", "How permanently removing tokens can affect supply.", "Beginner", "A burn destroys tokens or sends them to an address from which they cannot be spent. This can reduce supply under the project's accounting model.", "Burns matter economically only in relation to issuance and demand. A large burn can be less meaningful if new issuance is even larger."),
  make("09", "Buybacks", "When a protocol or company purchases its own token.", "Intermediate", "A buyback uses revenue or treasury assets to purchase tokens from the market. The tokens may be held, redistributed or burned.", "Buybacks connect business revenue with token demand, but their sustainability depends on actual cash flows and governance decisions."),
  make("10", "Staking", "Locking or delegating assets to participate in network security or rewards.", "Beginner", "Staking commonly involves committing tokens to a proof-of-stake network or staking contract in exchange for protocol-defined rewards.", "Reward rates should be evaluated against issuance, validator costs, lockup risk and token price changes rather than treated as free yield."),
  make("11", "Token utility", "Why a token is needed or used in an ecosystem.", "Beginner", "Utility can include paying fees, accessing features, governance, collateral or participation in network security.", "A token can have many uses, but utility alone does not guarantee demand. Users need a reason to acquire and retain it."),
  make("12", "Governance tokens", "Tokens used to influence protocol decisions.", "Intermediate", "Governance tokens can give holders voting rights over parameters, treasury spending or upgrades.", "Governance design determines who can propose, vote and execute changes. Token concentration can strongly influence outcomes."),
  make("13", "Treasuries", "Assets controlled by a protocol or organization.", "Intermediate", "A treasury holds resources that can fund development, incentives, grants or operations.", "Treasury composition and runway are useful when evaluating protocol sustainability. Governance often determines how funds are deployed."),
  make("14", "Protocol revenue", "Economic value generated by a blockchain application.", "Intermediate", "Protocol revenue can come from trading fees, borrowing interest, service fees or other application activity.", "Revenue should be separated from token incentives. A protocol can show high activity while spending even more on subsidies."),
  make("15", "Unit economics", "Understanding the economics of each user or transaction.", "Advanced", "Unit economics asks how much value an application creates relative to the cost of serving users or securing the network.", "In crypto, unit economics can include gas, liquidity incentives, validator rewards, acquisition costs and protocol fees."),
  make("16", "Fully diluted valuation", "A deeper look at future token supply.", "Beginner", "Fully diluted valuation estimates the value implied if the full planned token supply traded at the current price.", "FDV can reveal a large gap between today's circulating market cap and future supply. The gap is not automatically bearish, but it is important context."),
  make("17", "Emissions", "The rate at which new tokens enter an ecosystem.", "Intermediate", "Emissions describe scheduled or rule-based token distribution, often used to reward liquidity providers, stakers or contributors.", "Emission design affects incentives and dilution. Short-term incentives can attract liquidity but may not create durable demand."),
  make("18", "Liquidity mining", "Rewards designed to attract liquidity to a protocol.", "Intermediate", "Liquidity mining pays users for supplying assets to a market or pool, often with additional tokens.", "Liquidity mining can bootstrap markets but may attract mercenary capital that leaves when rewards fall."),
  make("19", "DEXs", "Decentralized exchanges that use smart contracts for trading.", "Beginner", "A decentralized exchange allows users to trade directly through smart contracts rather than handing custody to a centralized exchange.", "DEXs can use order books, automated market makers or hybrid models. Users take on smart-contract and transaction-execution risks."),
  make("20", "AMMs", "Automated market makers and algorithmic liquidity.", "Intermediate", "An AMM uses a mathematical rule and pooled assets to quote trades without requiring a traditional central order book.", "Constant-product pools are a common model. Large trades move the pool price and can create price impact for the trader."),
  make("21", "Liquidity pools", "Shared pools that provide assets for decentralized trading.", "Beginner", "Liquidity providers deposit assets into a smart-contract pool. Traders swap against that pool and pay fees.", "Providers can earn fees but face inventory risk and potential impermanent loss when the relative prices of pool assets change."),
  make("22", "Impermanent loss", "A key risk for liquidity providers.", "Intermediate", "Impermanent loss occurs when the value of assets in a liquidity pool differs from what the provider would have held by simply keeping the assets outside the pool.", "The loss becomes more or less significant depending on price divergence, fees earned and the AMM's curve."),
  make("23", "Lending protocols", "Smart-contract systems for borrowing and supplying assets.", "Beginner", "DeFi lending markets let users supply assets to earn interest while other users borrow against collateral.", "Risk comes from collateral volatility, oracle failures, smart-contract bugs and liquidation mechanisms."),
  make("24", "Collateral", "Assets pledged to support a loan.", "Beginner", "Collateral gives a lender protection if a borrower cannot repay. Crypto lending often requires overcollateralization.", "Collateral factors and liquidation thresholds control how much can be borrowed relative to deposited value."),
  make("25", "Liquidation in DeFi", "How lending protocols protect solvency.", "Intermediate", "When collateral value falls too far relative to debt, a protocol can allow liquidators to repay debt and receive collateral at a defined incentive.", "Liquidation parameters must balance capital efficiency with protocol safety. Poor settings can create cascading liquidations during crashes."),
  make("26", "Yield", "Where returns in DeFi actually come from.", "Beginner", "Yield can come from trading fees, lending interest, staking rewards, token emissions or combinations of these sources.", "Always identify the source of yield. High displayed APY can be driven primarily by token inflation rather than organic revenue."),
  make("27", "Protocol incentives", "How applications encourage users to provide liquidity or activity.", "Intermediate", "Protocols can distribute rewards to bootstrap markets, attract developers or encourage desired behaviors.", "Incentives work best when they lead to durable network effects. Otherwise users may leave as soon as rewards decline."),
  make("28", "Reading a token model", "A practical framework for evaluating token economics.", "Advanced", "When analyzing a token, examine supply, issuance, unlocks, utility, ownership concentration, liquidity, revenue and governance.", "The goal is to connect token design to actual economic behavior. A beautiful token model is less useful if users have no durable reason to participate."),
];

export const tracks: Track[] = [
  { slug: "crypto-101", number: "01", title: "Crypto 101", description: "Start from zero. Learn money, Bitcoin, blockchain, wallets and the vocabulary of crypto.", lessons: crypto101, accent: "mint" },
  { slug: "how-crypto-works", number: "02", title: "How Crypto Works", description: "Go beneath the surface: blocks, nodes, consensus, smart contracts and Layer 2s.", lessons: howCryptoWorks, accent: "violet" },
  { slug: "markets-trading", number: "03", title: "Markets & Trading", description: "Understand spot, futures, leverage, liquidation, liquidity, order books and funding.", lessons: markets, accent: "orange" },
  { slug: "tokenomics-defi", number: "04", title: "Tokenomics & DeFi", description: "Learn supply, unlocks, staking, burns, DEXs, AMMs, lending and protocol economics.", lessons: tokenomics, accent: "blue" },
];

export function getTrack(slug: string) { return tracks.find((track) => track.slug === slug); }
export function getLesson(trackSlug: string, lessonId: string) { return getTrack(trackSlug)?.lessons.find((lesson) => lesson.id === lessonId); }
